# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install
    npm run build     
  displayName: 'npm install and build'

- task: SnykSecurityScan@1
  inputs:
      serviceConnectionEndpoint: 'sekharreddy04631'
      testType: 'app'
      monitorWhen: 'always'
      failOnIssues: false
      projectName: 'sekharreddy0463'
      organization: 'sekharreddy0463'
      
- task: CmdLine@2
  inputs:
          script: |
            docker build -t new_image .
            docker images
